[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32/bin/ar"

[target.x86_64-apple-darwin]
linker = "clang"

[build]
target = "x86_64-apple-darwin"